In [1]:
import numpy as np
import random
m = 10
n = 10
# initialize blank board
base_array = np.zeros((m,n), dtype = int)

# randomly select number of cells to be initialized with starting state alive or value of 1
rand_num_ones = int(np.random.default_rng().random() * m * n)

# generate random numbers for row and column indices
rand_ms = np.random.default_rng().integers(low = 0, high = m, size = rand_num_ones)
rand_ns = np.random.default_rng().integers(low = 0, high = n, size = rand_num_ones)

# set random coordinates above equal to one in the base array of zeros.
for i in range(rand_num_ones):
    base_array[rand_ms[i], rand_ns[i]] = 1  
print(base_array)


[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 1 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1]]
